
# NB! Set your site's url, otherwise stuff will break :)

url: "https://cloud-parrot.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: 

# Google tracking id

google-tracking-id: "UA-124046744-1"

google_cse_id: "014694664375022079144:hoivop--bv4"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Harshal Rasal"
title: "Harshal Rasal"
description: "An Enthusiastic Linux Geek, Who loves working on OpenSource Technologies and A foodie by heart!"
keywords: "harshal, personal"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "<i>Dedicated to Embrace Linux</i>"
  - text: "<i>Strong affinity for OpenSource Softwares</i>"
  - text: "<i>Foodie by heart and Loves to travel</i>"

me-img: "/img/author.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: false
pinterest-share: false
pocket-share: false
vkontakte-share: false

disqus-shortname: "https-cloud-parrot-github-io"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/grad.jpg"
    date: "July 2013"
    description: "<small>Graduated! Ready to set the world on :fire:</small>"
  - image: "/img/timeline/cog.png"
    date: "April 2014"
    description: "<small>Started working at <a href='https://www.cognizant.com/' target='_blank'> Cognizant</a> :heart_eyes:</small>"
  - image: "/img/timeline/cog_work.png"
    date: "Linux & Virtualization Engineer"
    description: "<small>Responsibilities were to manage Bare-Metal and Vmware virtualized environments with Puppet</small>"
  - image: "/img/timeline/bye1.jpg"
    date: "November 2016"
    description: "<small>Farewell! I will miss you Cognizant :cry:</small>"
  - image: "/img/timeline/gl.png"
    date: "March 2017"
    description: "<small>Started as Devops Engineer at <a href='https://www.globallogic.com/' target='_blank'>Global Logic</a></small> :tada:"
  - image: "/img/timeline/devops.png"
    date: "Devops Engineer"
    description: "<small>From Ground to High-Up in AWS to Azure :cloud:, and back. The term 'DevOps' Sounds like music to my Ear's!</small>"


# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

#email: "yourname@mail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Harshal Rasal is an awesome person. Currently He lives in Binghamton, NY and works on multi dimensional projects. He usually spends his weekend in learning new stuffs, Reading, Cycling and Listening Music."
author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/harshalrasal007"
  - title: "twitter"
    url: "https://twitter.com/datacules"
  - title: "github"
    url: "https://github.com/cloud-parrot"
  - title: "linkedin"
    url: "https://linkedin.com/in/harshalrasal"
  - title: "rss"
    url: "/feed.xml"


#############
##LOGO IMAGE#
#############
site.logo_image: "/img/logo.png"
############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: godfatherisone
keybase-in-social: false
keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]


# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jemoji

theme: jekyll-theme-merlot
